"""
Cross-system anomaly detection between Salesforce (SFDC) opportunities
and SAP sales orders.

Detects:
- timing_gap        — large gap between SAP order creation and SFDC close date
- amount_discrepancy — material difference between SFDC amount and SAP netwr
- sequence_violation — SAP order created before SFDC opportunity was closed
- missing_handoff    — SFDC Closed Won with SAP order number but no SAP record

Field conventions (as generated by synthetic-data/src/generate_sfdc.py):
- SFDC opportunities: id, close_date (YYYY-MM-DD), amount, stage_name,
                      sap_order_id, is_won
- SAP orders:         vbeln, erdat (YYYY-MM-DD), netwr
- Matches:            sfdc_id, sap_id, confidence
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Date parsing
# ---------------------------------------------------------------------------


def parse_date(date_str: str) -> Optional[datetime]:
    """
    Parse a date string from ISO (YYYY-MM-DD) or YYYYMMDD format.

    Returns None for empty, None, or unparseable input.
    """
    if not date_str:
        return None
    for fmt in ("%Y-%m-%d", "%Y%m%d"):
        try:
            return datetime.strptime(date_str, fmt)
        except (ValueError, TypeError):
            pass
    return None


# ---------------------------------------------------------------------------
# Anomaly detection
# ---------------------------------------------------------------------------


def find_cross_system_anomalies(
    sfdc_opportunities: List[Dict[str, Any]],
    sap_orders: List[Dict[str, Any]],
    matches: List[Dict[str, Any]],
    gap_threshold_days: int = 30,
    amount_tolerance: float = 0.05,
) -> List[Dict[str, Any]]:
    """
    Find cross-system anomalies between SFDC opportunities and SAP orders.

    Anomaly types detected:

    1. timing_gap — |SAP erdat - SFDC close_date| > gap_threshold_days.
       Severity: high if gap > 60 days, medium otherwise.

    2. amount_discrepancy — |SFDC amount - SAP netwr| / max(amount, netwr) > amount_tolerance.
       Severity: high if relative discrepancy > 20%, medium otherwise.

    3. sequence_violation — SAP order creation date (erdat) is before SFDC
       opportunity close date. Always high severity.

    4. missing_handoff — SFDC opportunity has sap_order_id set and stage_name
       is "Closed Won" but no matching SAP record exists in sap_orders.
       Always high severity.

    Args:
        sfdc_opportunities: List of SFDC opportunity dicts (field: id, close_date,
                            amount, stage_name, sap_order_id, is_won)
        sap_orders:         List of SAP order dicts (fields: vbeln, erdat, netwr)
        matches:            List of match dicts (fields: sfdc_id, sap_id, confidence)
        gap_threshold_days: Days threshold for timing_gap detection (default 30)
        amount_tolerance:   Relative tolerance for amount_discrepancy (default 0.05)

    Returns:
        List of anomaly dicts, each with:
            type     : str  — anomaly type name
            severity : str  — "high" or "medium"
            sfdc_id  : str  — SFDC opportunity id (or "" if N/A)
            sap_id   : str  — SAP order vbeln (or "" if N/A)
            evidence : str  — human-readable description
    """
    anomalies: List[Dict[str, Any]] = []

    # Build lookup maps
    sap_by_vbeln: Dict[str, Dict[str, Any]] = {
        o["vbeln"]: o for o in sap_orders if "vbeln" in o
    }
    sfdc_by_id: Dict[str, Dict[str, Any]] = {
        o["id"]: o for o in sfdc_opportunities if "id" in o
    }

    # Build set of SAP vbelns that appear in matches (for missing_handoff check)
    matched_sap_ids: set = {m["sap_id"] for m in matches if "sap_id" in m}

    # --- Check each match for timing_gap, amount_discrepancy, sequence_violation ---
    for match in matches:
        sfdc_id = match.get("sfdc_id", "")
        sap_id = match.get("sap_id", "")

        sfdc_opp = sfdc_by_id.get(sfdc_id)
        sap_order = sap_by_vbeln.get(sap_id)

        if sfdc_opp is None or sap_order is None:
            continue

        sfdc_close = parse_date(sfdc_opp.get("close_date", ""))
        sap_erdat = parse_date(sap_order.get("erdat", ""))

        # 1. timing_gap
        if sfdc_close is not None and sap_erdat is not None:
            gap_days = abs((sap_erdat - sfdc_close).days)
            if gap_days > gap_threshold_days:
                severity = "high" if gap_days > 60 else "medium"
                anomalies.append(
                    {
                        "type": "timing_gap",
                        "severity": severity,
                        "sfdc_id": sfdc_id,
                        "sap_id": sap_id,
                        "evidence": (
                            f"Gap of {gap_days} days between SFDC close "
                            f"({sfdc_opp.get('close_date')}) and SAP erdat "
                            f"({sap_order.get('erdat')})"
                        ),
                    }
                )

            # 3. sequence_violation — SAP before SFDC close
            if sap_erdat < sfdc_close:
                anomalies.append(
                    {
                        "type": "sequence_violation",
                        "severity": "high",
                        "sfdc_id": sfdc_id,
                        "sap_id": sap_id,
                        "evidence": (
                            f"SAP order created ({sap_order.get('erdat')}) "
                            f"before SFDC close date ({sfdc_opp.get('close_date')})"
                        ),
                    }
                )

        # 2. amount_discrepancy
        sfdc_amount = sfdc_opp.get("amount")
        sap_netwr = sap_order.get("netwr")
        if sfdc_amount is not None and sap_netwr is not None:
            try:
                sfdc_amt = float(sfdc_amount)
                sap_amt = float(sap_netwr)
                denom = max(abs(sfdc_amt), abs(sap_amt))
                if denom > 0:
                    rel_diff = abs(sfdc_amt - sap_amt) / denom
                    if rel_diff > amount_tolerance:
                        severity = "high" if rel_diff > 0.20 else "medium"
                        anomalies.append(
                            {
                                "type": "amount_discrepancy",
                                "severity": severity,
                                "sfdc_id": sfdc_id,
                                "sap_id": sap_id,
                                "evidence": (
                                    f"Amount mismatch: SFDC={sfdc_amt:.2f}, "
                                    f"SAP={sap_amt:.2f}, "
                                    f"relative diff={rel_diff:.1%}"
                                ),
                            }
                        )
            except (TypeError, ValueError):
                pass

    # --- 4. missing_handoff ---
    # SFDC Closed Won with sap_order_id set but no matching SAP record found
    for opp in sfdc_opportunities:
        opp_id = opp.get("id", "")
        stage = opp.get("stage_name", "")
        sap_order_id = opp.get("sap_order_id") or opp.get("sap_order_number")

        is_closed_won = stage == "Closed Won" or opp.get("is_won", False)
        if not is_closed_won:
            continue
        if not sap_order_id:
            continue

        # Check if SAP record exists
        if sap_order_id not in sap_by_vbeln:
            anomalies.append(
                {
                    "type": "missing_handoff",
                    "severity": "high",
                    "sfdc_id": opp_id,
                    "sap_id": sap_order_id,
                    "evidence": (
                        f"SFDC Closed Won opportunity {opp_id} references "
                        f"SAP order {sap_order_id} but no matching SAP record found"
                    ),
                }
            )

    return anomalies


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


def compute_cross_system_metrics(
    sfdc_opportunities: List[Dict[str, Any]],
    sap_orders: List[Dict[str, Any]],
    matches: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Compute aggregate cross-system metrics.

    Returns a dict with:
        total_sfdc          : int   — total SFDC opportunities
        total_sap           : int   — total SAP orders
        total_matched       : int   — number of matched pairs
        unmatched_sfdc      : int   — SFDC opps with no SAP match
        unmatched_sap       : int   — SAP orders with no SFDC match
        avg_gap_days        : float — mean |erdat - close_date| across matched pairs
        match_rate          : float — total_matched / total_sfdc (0.0-1.0)
    """
    total_sfdc = len(sfdc_opportunities)
    total_sap = len(sap_orders)
    total_matched = len(matches)

    matched_sfdc_ids = {m["sfdc_id"] for m in matches if "sfdc_id" in m}
    matched_sap_ids = {m["sap_id"] for m in matches if "sap_id" in m}

    unmatched_sfdc = sum(
        1 for o in sfdc_opportunities if o.get("id", "") not in matched_sfdc_ids
    )
    unmatched_sap = sum(
        1 for o in sap_orders if o.get("vbeln", "") not in matched_sap_ids
    )

    # Build lookup maps for gap calculation
    sfdc_by_id: Dict[str, Dict[str, Any]] = {
        o["id"]: o for o in sfdc_opportunities if "id" in o
    }
    sap_by_vbeln: Dict[str, Dict[str, Any]] = {
        o["vbeln"]: o for o in sap_orders if "vbeln" in o
    }

    gap_days_list: List[float] = []
    for match in matches:
        sfdc_id = match.get("sfdc_id", "")
        sap_id = match.get("sap_id", "")
        sfdc_opp = sfdc_by_id.get(sfdc_id)
        sap_order = sap_by_vbeln.get(sap_id)
        if sfdc_opp is None or sap_order is None:
            continue
        sfdc_close = parse_date(sfdc_opp.get("close_date", ""))
        sap_erdat = parse_date(sap_order.get("erdat", ""))
        if sfdc_close is not None and sap_erdat is not None:
            gap_days_list.append(abs((sap_erdat - sfdc_close).days))

    avg_gap_days = sum(gap_days_list) / len(gap_days_list) if gap_days_list else 0.0
    match_rate = total_matched / total_sfdc if total_sfdc > 0 else 0.0

    return {
        "total_sfdc": total_sfdc,
        "total_sap": total_sap,
        "total_matched": total_matched,
        "unmatched_sfdc": unmatched_sfdc,
        "unmatched_sap": unmatched_sap,
        "avg_gap_days": avg_gap_days,
        "match_rate": match_rate,
    }
