#!/usr/bin/env bash
#
# bake-demo.sh — regenerate the static demo dashboard data.
#
# Produces, under demo/:
#   findings.json      — machine-readable forensic findings
#   findings-data.js   — same data wrapped as window.DEMO_FINDINGS (zero-install,
#                        loads via <script> so it works from file:// AND GitHub Pages)
#   report.md          — the full Markdown forensic report
#
# Deterministic: synthetic data is generated with seed 42, so the baked
# findings are identical on every run.
#
# Usage:  ./scripts/bake-demo.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="$(command -v python3 || command -v python)"

echo "[bake] Generating synthetic Salesforce + SAP data (seed 42)…"
cd "$ROOT/synthetic-data"
"$PYTHON" src/generate_sfdc.py --count 200 --accounts 50 --output sfdc_output/ --seed 42 >/dev/null

echo "[bake] Running forensic analysis…"
cd "$ROOT/pattern-engine"
PYTHONPATH=. "$PYTHON" scripts/analyze_sfdc.py --json "$ROOT/demo/findings.json" > "$ROOT/demo/report.md"

echo "[bake] Wrapping findings as embedded JS (window.DEMO_FINDINGS)…"
cd "$ROOT"
{
  printf '// Auto-generated by scripts/bake-demo.sh — do not edit by hand.\n'
  printf '// Lets the dashboard load with zero install (works from file:// and GitHub Pages).\n'
  printf 'window.DEMO_FINDINGS = '
  cat demo/findings.json
  printf ';\n'
} > demo/findings-data.js

echo "[bake] Rendering README preview banner from findings…"
"$PYTHON" scripts/make_preview_svg.py

echo "[bake] Done. Open demo/index.html or run: make demo-web"
