// Auto-generated by scripts/bake-demo.sh — do not edit by hand.
// Lets the dashboard load with zero install (works from file:// and GitHub Pages).
window.DEMO_FINDINGS = {
  "generated_at": "2026-06-11T06:23:33.322460+00:00",
  "dataset": {
    "opportunities": 214,
    "accounts": 50,
    "stage_histories": 1162,
    "activities": 1255,
    "line_items": 495,
    "sap_orders": 33,
    "event_log_records": 2417,
    "seed": 42
  },
  "headline": {
    "opportunities_analyzed": 214,
    "opportunities_flagged": 97,
    "anomaly_instances": 117,
    "anomaly_categories": 10,
    "cross_system_anomalies": 2,
    "high_severity_cross": 2,
    "sap_match_rate_pct": 15.4,
    "win_rate_pct": 55.3,
    "avg_deal_size": 261857.14,
    "median_cycle_days": 74
  },
  "anomalies": [
    {
      "flag": "QUARTER_END_COMPRESSION",
      "count": 32,
      "severity": "medium",
      "description": "Close dates clustered at quarter-end (pipeline gaming)",
      "examples": [
        {
          "id": "006000000000000015",
          "name": "Century Systems \u2014 New Business 601",
          "account_id": "001000000000000022",
          "amount": 306000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2024-06-30",
          "owner": "005000000000000017",
          "account_name": "Century Systems"
        },
        {
          "id": "006000000000000032",
          "name": "Pinnacle Enterprises \u2014 New Business 667",
          "account_id": "001000000000000012",
          "amount": 412000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2025-03-30",
          "owner": "005000000000000003",
          "account_name": "Pinnacle Enterprises"
        },
        {
          "id": "006000000000000038",
          "name": "Cobalt Ventures \u2014 New Business 199",
          "account_id": "001000000000000009",
          "amount": 240000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2024-06-28",
          "owner": "005000000000000012",
          "account_name": "Cobalt Ventures"
        },
        {
          "id": "006000000000000047",
          "name": "Cardinal Services \u2014 New Business 858",
          "account_id": "001000000000000016",
          "amount": 456000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2025-12-28",
          "owner": "005000000000000007",
          "account_name": "Cardinal Services"
        }
      ]
    },
    {
      "flag": "SPLIT_DEAL",
      "count": 28,
      "severity": "critical",
      "description": "Deal split across multiple opportunities to stay under approval thresholds",
      "examples": [
        {
          "id": "006000000000000005",
          "name": "Centric Group \u2014 Renewal 633",
          "account_id": "001000000000000029",
          "amount": 151000,
          "stage": "Closed Lost",
          "type": "Renewal",
          "close_date": "2025-08-04",
          "owner": "005000000000000006",
          "account_name": "Centric Group"
        },
        {
          "id": "006000000000000031",
          "name": "Cobalt Ventures \u2014 New Business 181",
          "account_id": "001000000000000009",
          "amount": 325000,
          "stage": "Perception Analysis",
          "type": "New Business",
          "close_date": "2025-09-25",
          "owner": "005000000000000002",
          "account_name": "Cobalt Ventures"
        },
        {
          "id": "006000000000000039",
          "name": "Pivot Group \u2014 New Business 882",
          "account_id": "001000000000000042",
          "amount": 300000,
          "stage": "Proposal/Price Quote",
          "type": "New Business",
          "close_date": "2024-03-13",
          "owner": "005000000000000016",
          "account_name": "Pivot Group"
        },
        {
          "id": "006000000000000041",
          "name": "Global Consulting \u2014 Renewal 844",
          "account_id": "001000000000000010",
          "amount": 456000,
          "stage": "Closed Won",
          "type": "Renewal",
          "close_date": "2025-05-09",
          "owner": "005000000000000014",
          "account_name": "Global Consulting"
        }
      ]
    },
    {
      "flag": "STALE_PIPELINE",
      "count": 15,
      "severity": "medium",
      "description": "Opportunity age far exceeds expected sales cycle",
      "examples": [
        {
          "id": "006000000000000008",
          "name": "Ignite Systems \u2014 Upsell 506",
          "account_id": "001000000000000050",
          "amount": 474000,
          "stage": "Proposal",
          "type": "Upsell",
          "close_date": "2024-10-14",
          "owner": "005000000000000006",
          "account_name": "Ignite Systems"
        },
        {
          "id": "006000000000000028",
          "name": "Tangent Solutions \u2014 New Business 389",
          "account_id": "001000000000000033",
          "amount": 91000,
          "stage": "Negotiation/Review",
          "type": "New Business",
          "close_date": "2025-09-03",
          "owner": "005000000000000006",
          "account_name": "Tangent Solutions"
        },
        {
          "id": "006000000000000031",
          "name": "Cobalt Ventures \u2014 New Business 181",
          "account_id": "001000000000000009",
          "amount": 325000,
          "stage": "Perception Analysis",
          "type": "New Business",
          "close_date": "2025-09-25",
          "owner": "005000000000000002",
          "account_name": "Cobalt Ventures"
        },
        {
          "id": "006000000000000095",
          "name": "Rocket Technologies \u2014 New Business 933",
          "account_id": "001000000000000019",
          "amount": 287000,
          "stage": "Proposal/Price Quote",
          "type": "New Business",
          "close_date": "2024-05-25",
          "owner": "005000000000000009",
          "account_name": "Rocket Technologies"
        }
      ]
    },
    {
      "flag": "AMOUNT_INFLATION",
      "count": 14,
      "severity": "critical",
      "description": "Deal amount inflated relative to account history",
      "examples": [
        {
          "id": "006000000000000007",
          "name": "Prism Ventures \u2014 Renewal 767",
          "account_id": "001000000000000031",
          "amount": 85000,
          "stage": "Proposal",
          "type": "Renewal",
          "close_date": "2024-05-20",
          "owner": "005000000000000001",
          "account_name": "Prism Ventures"
        },
        {
          "id": "006000000000000033",
          "name": "Radius Inc \u2014 New Business 509",
          "account_id": "001000000000000049",
          "amount": 720000,
          "stage": "Proposal/Price Quote",
          "type": "New Business",
          "close_date": "2024-05-27",
          "owner": "005000000000000007",
          "account_name": "Radius Inc"
        },
        {
          "id": "006000000000000035",
          "name": "Centric Group \u2014 Renewal 397",
          "account_id": "001000000000000029",
          "amount": 70000,
          "stage": "Proposal",
          "type": "Renewal",
          "close_date": "2025-07-27",
          "owner": "005000000000000006",
          "account_name": "Centric Group"
        },
        {
          "id": "006000000000000039",
          "name": "Pivot Group \u2014 New Business 882",
          "account_id": "001000000000000042",
          "amount": 300000,
          "stage": "Proposal/Price Quote",
          "type": "New Business",
          "close_date": "2024-03-13",
          "owner": "005000000000000016",
          "account_name": "Pivot Group"
        }
      ]
    },
    {
      "flag": "GHOST_PIPELINE",
      "count": 10,
      "severity": "medium",
      "description": "No activity logged after initial creation (abandoned opportunity)",
      "examples": [
        {
          "id": "006000000000000028",
          "name": "Tangent Solutions \u2014 New Business 389",
          "account_id": "001000000000000033",
          "amount": 91000,
          "stage": "Negotiation/Review",
          "type": "New Business",
          "close_date": "2025-09-03",
          "owner": "005000000000000006",
          "account_name": "Tangent Solutions"
        },
        {
          "id": "006000000000000058",
          "name": "Centric Corp \u2014 Renewal 870",
          "account_id": "001000000000000048",
          "amount": 119000,
          "stage": "Proposal",
          "type": "Renewal",
          "close_date": "2025-05-06",
          "owner": "005000000000000020",
          "account_name": "Centric Corp"
        },
        {
          "id": "006000000000000068",
          "name": "Sync Partners \u2014 New Business 979",
          "account_id": "001000000000000018",
          "amount": 194000,
          "stage": "Proposal/Price Quote",
          "type": "New Business",
          "close_date": "2026-01-06",
          "owner": "005000000000000017",
          "account_name": "Sync Partners"
        },
        {
          "id": "006000000000000080",
          "name": "Delta Industries \u2014 New Business 277",
          "account_id": "001000000000000026",
          "amount": 496000,
          "stage": "Negotiation/Review",
          "type": "New Business",
          "close_date": "2025-08-19",
          "owner": "005000000000000002",
          "account_name": "Delta Industries"
        }
      ]
    },
    {
      "flag": "SPEED_ANOMALY",
      "count": 8,
      "severity": "low",
      "description": "Stage progression far faster or slower than baseline",
      "examples": [
        {
          "id": "006000000000000048",
          "name": "Uplift Consulting \u2014 Renewal 159",
          "account_id": "001000000000000025",
          "amount": 83000,
          "stage": "Closed Won",
          "type": "Renewal",
          "close_date": "2025-05-02",
          "owner": "005000000000000006",
          "account_name": "Uplift Consulting"
        },
        {
          "id": "006000000000000072",
          "name": "Horizon Corp \u2014 Upsell 802",
          "account_id": "001000000000000035",
          "amount": 56000,
          "stage": "Closed Won",
          "type": "Upsell",
          "close_date": "2024-08-01",
          "owner": "005000000000000012",
          "account_name": "Horizon Corp"
        },
        {
          "id": "006000000000000146",
          "name": "Lumina Partners \u2014 Renewal 224",
          "account_id": "001000000000000028",
          "amount": 428000,
          "stage": "Closed Won",
          "type": "Renewal",
          "close_date": "2024-03-15",
          "owner": "005000000000000013",
          "account_name": "Lumina Partners"
        },
        {
          "id": "006000000000000154",
          "name": "Inland Services \u2014 New Business 674",
          "account_id": "001000000000000008",
          "amount": 296000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2025-09-28",
          "owner": "005000000000000013",
          "account_name": "Inland Services"
        }
      ]
    },
    {
      "flag": "STAGE_SKIP",
      "count": 3,
      "severity": "high",
      "description": "One or more mandatory pipeline stages skipped",
      "examples": [
        {
          "id": "006000000000000038",
          "name": "Cobalt Ventures \u2014 New Business 199",
          "account_id": "001000000000000009",
          "amount": 240000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2024-06-28",
          "owner": "005000000000000012",
          "account_name": "Cobalt Ventures"
        },
        {
          "id": "006000000000000130",
          "name": "Tangent Enterprises \u2014 New Business 983",
          "account_id": "001000000000000040",
          "amount": 299000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2025-03-21",
          "owner": "005000000000000006",
          "account_name": "Tangent Enterprises"
        },
        {
          "id": "006000000000000162",
          "name": "Inland Services \u2014 New Business 384",
          "account_id": "001000000000000008",
          "amount": 84000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2024-07-26",
          "owner": "005000000000000020",
          "account_name": "Inland Services"
        }
      ]
    },
    {
      "flag": "STAGE_REGRESSION",
      "count": 3,
      "severity": "high",
      "description": "Stage moved backward (e.g., from Proposal back to Prospecting)",
      "examples": [
        {
          "id": "006000000000000089",
          "name": "Rocket Technologies \u2014 Renewal 972",
          "account_id": "001000000000000019",
          "amount": 465000,
          "stage": "Closed Won",
          "type": "Renewal",
          "close_date": "2025-03-31",
          "owner": "005000000000000012",
          "account_name": "Rocket Technologies"
        },
        {
          "id": "006000000000000139",
          "name": "Century Corp \u2014 New Business 425",
          "account_id": "001000000000000036",
          "amount": 312000,
          "stage": "Perception Analysis",
          "type": "New Business",
          "close_date": "2025-03-04",
          "owner": "005000000000000012",
          "account_name": "Century Corp"
        },
        {
          "id": "006000000000000180",
          "name": "Radius Inc \u2014 New Business 467",
          "account_id": "001000000000000049",
          "amount": 783000,
          "stage": "Negotiation/Review",
          "type": "New Business",
          "close_date": "2025-09-03",
          "owner": "005000000000000005",
          "account_name": "Radius Inc"
        }
      ]
    },
    {
      "flag": "CROSS_SYSTEM_GAP",
      "count": 2,
      "severity": "high",
      "description": "Large timing gap between SFDC close and SAP order creation",
      "examples": [
        {
          "id": "006000000000000038",
          "name": "Cobalt Ventures \u2014 New Business 199",
          "account_id": "001000000000000009",
          "amount": 240000,
          "stage": "Closed Won",
          "type": "New Business",
          "close_date": "2024-06-28",
          "owner": "005000000000000012",
          "account_name": "Cobalt Ventures"
        },
        {
          "id": "006000000000000102",
          "name": "Global Ventures \u2014 Renewal 652",
          "account_id": "001000000000000041",
          "amount": 292000,
          "stage": "Closed Won",
          "type": "Renewal",
          "close_date": "2025-09-02",
          "owner": "005000000000000001",
          "account_name": "Global Ventures"
        }
      ]
    },
    {
      "flag": "OWNER_SWAP_AT_CLOSE",
      "count": 2,
      "severity": "high",
      "description": "Owner changed within final stage before close",
      "examples": [
        {
          "id": "006000000000000140",
          "name": "Falcon Systems \u2014 Upsell 463",
          "account_id": "001000000000000045",
          "amount": 429000,
          "stage": "Closed Won",
          "type": "Upsell",
          "close_date": "2025-12-23",
          "owner": "005000000000000020",
          "account_name": "Falcon Systems"
        },
        {
          "id": "006000000000000189",
          "name": "Tangent Solutions \u2014 Renewal 227",
          "account_id": "001000000000000033",
          "amount": 34000,
          "stage": "Closed Won",
          "type": "Renewal",
          "close_date": "2025-02-14",
          "owner": "005000000000000004",
          "account_name": "Tangent Solutions"
        }
      ]
    }
  ],
  "cross_system": {
    "total_sfdc": 214,
    "total_sap": 33,
    "matched_pairs": 33,
    "match_rate_pct": 15.4,
    "avg_gap_days": 9.7,
    "anomaly_count": 2,
    "examples": [
      {
        "type": "timing_gap",
        "severity": "high",
        "evidence": "Gap of 84 days between SFDC close (2024-06-28) and SAP erdat (2024-09-20)",
        "sfdc_id": "006000000000000038",
        "sap_id": "SAP7192640"
      },
      {
        "type": "timing_gap",
        "severity": "high",
        "evidence": "Gap of 79 days between SFDC close (2025-09-02) and SAP erdat (2025-11-20)",
        "sfdc_id": "006000000000000102",
        "sap_id": "SAP8166143"
      }
    ]
  },
  "conformance": {
    "model": "sfdc_new_business",
    "total_cases": 131,
    "conformant_cases": 131,
    "conformance_rate_pct": 100.0,
    "average_fitness": 0.6912,
    "total_deviations": 271,
    "deviation_types": {
      "skipped_activity": 25,
      "wrong_order": 22,
      "missing_activity": 222,
      "duplicate_activity": 2
    }
  },
  "quarter_end": {
    "months": [
      {
        "month": 1,
        "count": 2,
        "is_qtr_end": false
      },
      {
        "month": 2,
        "count": 2,
        "is_qtr_end": false
      },
      {
        "month": 3,
        "count": 11,
        "is_qtr_end": true
      },
      {
        "month": 4,
        "count": 6,
        "is_qtr_end": false
      },
      {
        "month": 5,
        "count": 8,
        "is_qtr_end": false
      },
      {
        "month": 6,
        "count": 18,
        "is_qtr_end": true
      },
      {
        "month": 7,
        "count": 5,
        "is_qtr_end": false
      },
      {
        "month": 8,
        "count": 11,
        "is_qtr_end": false
      },
      {
        "month": 9,
        "count": 16,
        "is_qtr_end": true
      },
      {
        "month": 10,
        "count": 8,
        "is_qtr_end": false
      },
      {
        "month": 11,
        "count": 7,
        "is_qtr_end": false
      },
      {
        "month": 12,
        "count": 20,
        "is_qtr_end": true
      }
    ],
    "qtr_end_count": 65,
    "total_closed": 114,
    "qtr_end_pct": 57.0,
    "expected_pct": 33.3,
    "ratio": 1.7
  },
  "stage_distribution": [
    {
      "stage": "Closed Won",
      "count": 63
    },
    {
      "stage": "Closed Lost",
      "count": 51
    },
    {
      "stage": "Perception Analysis",
      "count": 28
    },
    {
      "stage": "Negotiation/Review",
      "count": 21
    },
    {
      "stage": "Proposal",
      "count": 20
    },
    {
      "stage": "Proposal/Price Quote",
      "count": 17
    },
    {
      "stage": "Qualification",
      "count": 10
    },
    {
      "stage": "Discovery",
      "count": 2
    },
    {
      "stage": "Negotiation",
      "count": 2
    }
  ]
};
